-- =============================================================================
-- Seed Data for canonical_objects
-- =============================================================================
-- This file contains sample data for testing canonical_objects functionality.
-- Run this after migrations are complete.

-- Clean existing test data (optional)
-- DELETE FROM canonical_objects WHERE id LIKE 'github|test%' OR id LIKE 'notion|test%';

-- =============================================================================
-- GITHUB ISSUE EXAMPLES
-- =============================================================================

-- GitHub Issue #1: Feature request for SSO
INSERT INTO canonical_objects (
  id,
  platform,
  object_type,
  title,
  body,
  attachments,
  actors,
  timestamps,
  relations,
  properties,
  summary,
  search_text,
  semantic_hash,
  visibility,
  raw
) VALUES (
  'github|acme|issue|123',
  'github',
  'issue',
  'Add SSO authentication support',
  'We need to implement single sign-on authentication for enterprise customers. This should support OAuth 2.0 and SAML protocols, with priority on Microsoft Azure AD and Google Workspace integration.

## Requirements
- OAuth 2.0 support
- SAML 2.0 support
- Azure AD integration
- Google Workspace integration
- Admin dashboard for SSO configuration

## Business Impact
Enterprise customers are requiring SSO before they can proceed with adoption. This is blocking 3 major deals totaling $500K ARR.',
  '[
    {
      "id": "att_design_doc",
      "type": "link",
      "name": "SSO Design Document",
      "url": "https://docs.google.com/document/d/abc123"
    }
  ]'::jsonb,
  '{
    "created_by": "user:alice",
    "assignees": ["user:bob", "user:carol"],
    "participants": ["user:alice", "user:bob", "user:carol", "user:dave"]
  }'::jsonb,
  '{
    "created_at": "2025-11-18T10:00:00Z",
    "updated_at": "2025-11-20T15:30:00Z",
    "closed_at": null
  }'::jsonb,
  '{
    "repo_id": "github|acme/auth-service",
    "project_id": "proj_enterprise_features",
    "linked_prs": ["github|acme|pr|456"]
  }'::jsonb,
  '{
    "labels": ["feature", "security", "enterprise", "P0"],
    "status": "open",
    "priority": "P0",
    "milestone": "Q1 2026",
    "url": "https://github.com/acme/auth-service/issues/123",
    "state": "open"
  }'::jsonb,
  '{
    "short": "Add SSO authentication for enterprise customers",
    "medium": "Implement single sign-on authentication using OAuth 2.0 and SAML protocols for enterprise customers, prioritizing Azure AD and Google Workspace",
    "long": "This feature request involves implementing SSO authentication to allow enterprise customers to log in using their corporate credentials. The implementation should support OAuth 2.0 and SAML protocols, with priority on Microsoft Azure AD and Google Workspace integration. This is currently blocking 3 major enterprise deals worth $500K in annual recurring revenue.",
    "keywords": ["SSO", "authentication", "OAuth", "SAML", "enterprise", "security"]
  }'::jsonb,
  null,  -- search_text will be auto-generated by trigger
  'sso_auth_feature_2025_q1_abc123',
  'team',
  '{
    "number": 123,
    "state": "open",
    "locked": false,
    "comments": 15,
    "reactions": {
      "thumbs_up": 8,
      "thumbs_down": 0,
      "hooray": 3
    }
  }'::jsonb
);

-- GitHub Issue #2: Bug report for API rate limiting
INSERT INTO canonical_objects (
  id,
  platform,
  object_type,
  title,
  body,
  actors,
  timestamps,
  relations,
  properties,
  visibility
) VALUES (
  'github|acme|issue|124',
  'github',
  'issue',
  'API rate limiting not working correctly',
  'The API rate limiting is not correctly counting requests. Users are able to exceed the 1000 req/hour limit without getting 429 responses.

## Steps to Reproduce
1. Make 1500 API calls within an hour
2. Observe that no 429 errors are returned
3. Check rate limit headers - they show incorrect counts

## Expected Behavior
After 1000 requests in an hour, subsequent requests should return 429 with proper Retry-After headers.

## Current Behavior
All requests succeed regardless of count.',
  '{
    "created_by": "user:eve",
    "assignees": ["user:bob"]
  }'::jsonb,
  '{
    "created_at": "2025-11-19T08:15:00Z",
    "updated_at": "2025-11-19T14:20:00Z"
  }'::jsonb,
  '{
    "repo_id": "github|acme/api-gateway"
  }'::jsonb,
  '{
    "labels": ["bug", "api", "P1"],
    "status": "in_progress",
    "priority": "P1",
    "url": "https://github.com/acme/api-gateway/issues/124"
  }'::jsonb,
  'team'
);

-- =============================================================================
-- GITHUB PULL REQUEST EXAMPLE
-- =============================================================================

INSERT INTO canonical_objects (
  id,
  platform,
  object_type,
  title,
  body,
  actors,
  timestamps,
  relations,
  properties,
  visibility
) VALUES (
  'github|acme|pr|456',
  'github',
  'pr',
  'Implement OAuth 2.0 SSO provider',
  'This PR implements the OAuth 2.0 provider for SSO authentication as part of issue #123.

## Changes
- Added OAuth 2.0 authorization server
- Implemented token generation and validation
- Added Azure AD integration
- Created admin UI for OAuth client management

## Testing
- Unit tests for OAuth flow
- Integration tests with Azure AD
- Manual testing with test tenant

## Security Review
Security team has reviewed the implementation and approved it.',
  '{
    "created_by": "user:bob",
    "reviewers": ["user:carol", "user:dave"],
    "participants": ["user:bob", "user:carol", "user:dave", "user:alice"]
  }'::jsonb,
  '{
    "created_at": "2025-11-19T11:00:00Z",
    "updated_at": "2025-11-20T16:45:00Z",
    "merged_at": null
  }'::jsonb,
  '{
    "repo_id": "github|acme/auth-service",
    "linked_issues": ["github|acme|issue|123"]
  }'::jsonb,
  '{
    "labels": ["feature", "security"],
    "status": "open",
    "url": "https://github.com/acme/auth-service/pull/456",
    "state": "open",
    "review_status": "approved"
  }'::jsonb,
  'team'
);

-- =============================================================================
-- NOTION PAGE EXAMPLES
-- =============================================================================

-- Notion Page #1: User Interview Notes
INSERT INTO canonical_objects (
  id,
  platform,
  object_type,
  title,
  body,
  attachments,
  actors,
  timestamps,
  relations,
  properties,
  summary,
  visibility
) VALUES (
  'notion|workspace_abc|page|xyz001',
  'notion',
  'page',
  'User Interview - Acme Corp (Enterprise)',
  '# User Interview - Acme Corp
Date: November 18, 2025
Interviewer: Alice
Participant: John Smith (CTO, Acme Corp)

## Key Points
- Acme Corp has 5000 employees
- Currently using on-prem SSO solution (Okta)
- Want to migrate to cloud-based solution
- Main pain point: Cannot use our product without SSO
- Budget approved: $100K/year
- Decision timeline: Q1 2026

## Requirements
1. SSO with Azure AD integration (mandatory)
2. SCIM provisioning (nice to have)
3. Audit logs (mandatory)
4. Custom branding (nice to have)

## Next Steps
- Schedule technical deep-dive with their security team
- Provide SSO implementation timeline
- Send pricing proposal for enterprise tier',
  '[
    {
      "id": "recording_001",
      "type": "link",
      "name": "Interview Recording",
      "url": "https://zoom.us/rec/abc123"
    }
  ]'::jsonb,
  '{
    "created_by": "user:alice",
    "participants": ["user:alice", "user:bob"]
  }'::jsonb,
  '{
    "created_at": "2025-11-18T14:00:00Z",
    "updated_at": "2025-11-18T15:30:00Z"
  }'::jsonb,
  '{
    "database_id": "notion|workspace_abc|db|user_interviews"
  }'::jsonb,
  '{
    "tags": ["user-interview", "enterprise", "sso"],
    "status": "completed",
    "company": "Acme Corp",
    "deal_size": "$100K ARR",
    "urgency": "high"
  }'::jsonb,
  '{
    "short": "User interview with Acme Corp about SSO requirements",
    "medium": "Enterprise customer interview discussing SSO requirements for 5000 employees, Azure AD integration, and $100K budget approved for Q1 2026",
    "long": "Detailed user interview with Acme Corp CTO discussing their requirement for SSO authentication to enable product adoption. They have 5000 employees currently using Okta on-prem and want to migrate to cloud. Main blocker is lack of SSO support. Budget of $100K/year approved with Q1 2026 decision timeline. Key requirements include Azure AD integration, audit logs, and optionally SCIM provisioning and custom branding.",
    "keywords": ["user-interview", "enterprise", "SSO", "Azure AD", "Acme Corp", "security"]
  }'::jsonb,
  'team'
);

-- Notion Page #2: Product Feedback
INSERT INTO canonical_objects (
  id,
  platform,
  object_type,
  title,
  body,
  actors,
  timestamps,
  relations,
  properties,
  visibility
) VALUES (
  'notion|workspace_abc|page|xyz002',
  'notion',
  'page',
  'Product Feedback - API Rate Limiting Issues',
  '# Product Feedback - Beta Customer

## Source
Beta customer reported via email on Nov 19, 2025

## Issue
API rate limiting is not working as expected. Customer was able to make unlimited requests without hitting rate limits.

## Impact
- Customer confused about actual rate limits
- Potential for abuse by bad actors
- Need to fix before GA launch

## Customer Quote
"We tried to test the rate limits and were surprised that we could make 5000 requests without any throttling. The documentation says 1000/hour but that doesn''t seem to be enforced."

## Action Items
- Investigate rate limiting implementation
- Create GitHub issue to track fix
- Inform customer of fix timeline',
  '{
    "created_by": "user:eve",
    "participants": ["user:eve", "user:bob"]
  }'::jsonb,
  '{
    "created_at": "2025-11-19T09:00:00Z",
    "updated_at": "2025-11-19T09:30:00Z"
  }'::jsonb,
  '{
    "database_id": "notion|workspace_abc|db|product_feedback"
  }'::jsonb,
  '{
    "tags": ["feedback", "bug", "api", "rate-limiting"],
    "status": "in-review",
    "severity": "high",
    "customer": "Beta Customer",
    "source": "email"
  }'::jsonb,
  'team'
);

-- =============================================================================
-- SLACK MESSAGE EXAMPLE
-- =============================================================================

INSERT INTO canonical_objects (
  id,
  platform,
  object_type,
  title,
  body,
  actors,
  timestamps,
  relations,
  properties,
  visibility
) VALUES (
  'slack|team_abc|message|msg001',
  'slack',
  'message',
  null,
  '@bob FYI - just got off a call with Acme Corp. They love the product but absolutely need SSO before they can move forward. This is blocking a $100K deal. Can we prioritize this for Q1?',
  '{
    "created_by": "user:alice",
    "mentioned": ["user:bob"]
  }'::jsonb,
  '{
    "created_at": "2025-11-18T15:45:00Z",
    "updated_at": "2025-11-18T15:45:00Z"
  }'::jsonb,
  '{
    "channel_id": "slack|team_abc|channel_sales",
    "thread_id": null
  }'::jsonb,
  '{
    "channel_name": "#sales",
    "url": "https://team-abc.slack.com/archives/C123/p16001234567890"
  }'::jsonb,
  'team'
);

-- =============================================================================
-- Summary
-- =============================================================================

-- Check inserted data
SELECT
  platform,
  object_type,
  COUNT(*) as count
FROM canonical_objects
WHERE deleted_at IS NULL
GROUP BY platform, object_type
ORDER BY platform, object_type;

-- Display sample data
SELECT
  id,
  platform,
  object_type,
  title,
  properties->>'status' as status,
  (timestamps->>'created_at')::timestamptz as created_at
FROM canonical_objects
WHERE deleted_at IS NULL
ORDER BY (timestamps->>'created_at')::timestamptz DESC;
