/**
 * Synthetic Data Loader
 * Loads graph datasets generated by scripts/generate-graph-dataset
 */

import * as fs from 'fs';
import * as path from 'path';

// Types from graph dataset generator
export interface Company {
  id: string;
  name: string;
  tier: 'enterprise' | 'growth' | 'startup';
  employee_count: number;
  industry: string;
  created_at: string;
  metadata?: Record<string, any>;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: 'customer' | 'support' | 'engineering' | 'sales' | 'product';
  company_id?: string;
  avatar_url?: string;
  created_at: string;
  metadata?: Record<string, any>;
}

export interface SlackMessage {
  ts: string;
  user_id: string;
  text: string;
  thread_ts?: string;
  reactions?: Array<{
    name: string;
    count: number;
    users: string[];
  }>;
  attachments?: Array<{
    title?: string;
    text?: string;
    fields?: Array<{ title: string; value: string; short?: boolean }>;
    footer?: string;
    color?: string;
  }>;
  bot_id?: string;
  created_at: string;
}

export interface SlackThread {
  ts: string;
  channel: string;
  messages: SlackMessage[];

  // Relations
  triggered_by_ticket?: string;
  resulted_in_issue?: string;

  // Participants
  participants: string[];

  // Context
  keywords: string[];
  sentiment?: 'positive' | 'neutral' | 'concerned' | 'urgent';

  // Decision tracking
  decision_made: boolean;
  decided_by?: string;
  decided_at?: string;

  created_at: string;
  updated_at: string;
  metadata?: Record<string, any>;
}

export interface ZendeskTicket {
  id: number;
  subject: string;
  description: string;
  status: string;
  priority: string;
  type: string;
  organization_id?: string;
  requester_id: string;
  assignee_id?: string;
  tags: string[];
  custom_fields: Array<{ id: number; value: any }>;
  created_at: string;
  updated_at: string;
  comments?: Array<{
    id: number;
    author_id: string;
    body: string;
    created_at: string;
  }>;
}

export interface LinearIssue {
  id: string;
  identifier: string;
  title: string;
  description: string;
  state: { id: string; name: string; type: string };
  priority: number;
  labels: Array<{ id: string; name: string }>;
  team: { id: string; key: string; name: string };
  creator: { id: string; name: string; email: string };
  assignee?: { id: string; name: string; email: string };
  parent?: { id: string; identifier: string };
  created_at: string;
  updated_at: string;
  comments?: Array<{
    id: string;
    body: string;
    user: { id: string; name: string };
    created_at: string;
  }>;
}

export type RelationType =
  | 'triggered_by'
  | 'resulted_in'
  | 'belongs_to'
  | 'assigned_to'
  | 'created_by'
  | 'decided_by'
  | 'participated_in'
  | 'similar_to'
  | 'duplicate_of'
  | 'related_to';

export interface RelationHint {
  from_id: string;
  to_id: string;
  type: RelationType;
  confidence?: number;
  source: 'explicit' | 'inferred' | 'computed';
  metadata?: Record<string, any>;
  created_at: string;
}

export interface GraphDataset {
  metadata: {
    scenario: string;
    generated_at: string;
    version: string;
    stats: {
      companies: number;
      users: number;
      zendesk_tickets: number;
      slack_threads: number;
      linear_issues: number;
      relations: number;
    };
  };

  companies: Company[];
  users: User[];
  zendesk_tickets: ZendeskTicket[];
  slack_threads: SlackThread[];
  linear_issues: LinearIssue[];
  relations: RelationHint[];
}

export class SyntheticDataLoader {
  private dataDir: string;

  constructor(dataDir: string = 'data/graph-datasets') {
    this.dataDir = path.resolve(process.cwd(), dataDir);

    // Verify directory exists
    if (!fs.existsSync(this.dataDir)) {
      throw new Error(`Data directory not found: ${this.dataDir}`);
    }
  }

  /**
   * Load a specific scenario dataset
   */
  loadDataset(scenario: string): GraphDataset {
    const filePath = path.join(this.dataDir, `${scenario}.json`);

    if (!fs.existsSync(filePath)) {
      throw new Error(`Dataset not found: ${scenario} (${filePath})`);
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const dataset: GraphDataset = JSON.parse(content);

    // Validate dataset structure
    this.validateDataset(dataset, scenario);

    return dataset;
  }

  /**
   * Get list of all available scenarios
   */
  getAllScenarios(): string[] {
    const files = fs.readdirSync(this.dataDir);
    return files.filter((f) => f.endsWith('.json')).map((f) => f.replace('.json', ''));
  }

  /**
   * Load all datasets (useful for batch processing)
   */
  loadAllDatasets(): Record<string, GraphDataset> {
    const scenarios = this.getAllScenarios();
    const datasets: Record<string, GraphDataset> = {};

    for (const scenario of scenarios) {
      datasets[scenario] = this.loadDataset(scenario);
    }

    return datasets;
  }

  /**
   * Get dataset statistics
   */
  getDatasetStats(scenario: string): GraphDataset['metadata']['stats'] {
    const dataset = this.loadDataset(scenario);
    return dataset.metadata.stats;
  }

  /**
   * Validate dataset structure
   */
  private validateDataset(dataset: GraphDataset, scenario: string): void {
    if (!dataset.metadata) {
      throw new Error(`Invalid dataset ${scenario}: missing metadata`);
    }

    if (!dataset.companies || !Array.isArray(dataset.companies)) {
      throw new Error(`Invalid dataset ${scenario}: missing or invalid companies`);
    }

    if (!dataset.users || !Array.isArray(dataset.users)) {
      throw new Error(`Invalid dataset ${scenario}: missing or invalid users`);
    }

    if (!dataset.zendesk_tickets || !Array.isArray(dataset.zendesk_tickets)) {
      throw new Error(`Invalid dataset ${scenario}: missing or invalid zendesk_tickets`);
    }

    if (!dataset.slack_threads || !Array.isArray(dataset.slack_threads)) {
      throw new Error(`Invalid dataset ${scenario}: missing or invalid slack_threads`);
    }

    if (!dataset.linear_issues || !Array.isArray(dataset.linear_issues)) {
      throw new Error(`Invalid dataset ${scenario}: missing or invalid linear_issues`);
    }

    if (!dataset.relations || !Array.isArray(dataset.relations)) {
      throw new Error(`Invalid dataset ${scenario}: missing or invalid relations`);
    }
  }

  /**
   * Find object by ID across all entity types
   */
  findObject(
    dataset: GraphDataset,
    id: string
  ): Company | User | ZendeskTicket | SlackThread | LinearIssue | null {
    // Try companies
    const company = dataset.companies.find((c) => c.id === id);
    if (company) return company;

    // Try users
    const user = dataset.users.find((u) => u.id === id);
    if (user) return user;

    // Try Zendesk tickets
    const ticket = dataset.zendesk_tickets.find((t) => String(t.id) === id);
    if (ticket) return ticket;

    // Try Slack threads
    const thread = dataset.slack_threads.find((t) => t.ts === id);
    if (thread) return thread;

    // Try Linear issues
    const issue = dataset.linear_issues.find((i) => i.identifier === id);
    if (issue) return issue;

    return null;
  }

  /**
   * Get relations for a specific object
   */
  getRelationsFor(dataset: GraphDataset, objectId: string): RelationHint[] {
    return dataset.relations.filter((r) => r.from_id === objectId || r.to_id === objectId);
  }

  /**
   * Get relations by type
   */
  getRelationsByType(dataset: GraphDataset, type: RelationType): RelationHint[] {
    return dataset.relations.filter((r) => r.type === type);
  }
}
