import { NextResponse } from 'next/server';

export interface LinearIssue {
  id: string;
  platform: 'linear';
  object_type: string;
  title: string;
  body: string;
  actor: string;
  timestamp: string;
  status: string;
}

// Linear issues from "Momo v4." project - 49 total (30 Done, 19 Canceled)
const MOMO_LINEAR_DATA: LinearIssue[] = [
  // Done issues (30)
  {
    id: 'TEN-190',
    platform: 'linear',
    object_type: 'issue',
    title: 'dark mode bug broooo',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-10-22',
    status: 'Done',
  },
  {
    id: 'TEN-189',
    platform: 'linear',
    object_type: 'issue',
    title: 'smoother onboarding',
    body: 'for slack, need to automatically show the channels that the user is mentioned in',
    actor: 'Cailyn Yong',
    timestamp: '2025-10-22',
    status: 'Done',
  },
  {
    id: 'TEN-188',
    platform: 'linear',
    object_type: 'issue',
    title: "AI filtering todo/followup based on user's rules input",
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-10-22',
    status: 'Done',
  },
  {
    id: 'TEN-179',
    platform: 'linear',
    object_type: 'issue',
    title: 'Unified chat input sidebar with momo toggle',
    body: 'Build unified chat interface for all different platforms',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-27',
    status: 'Done',
  },
  {
    id: 'TEN-174',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement Gmail polling for real-time email updates',
    body: 'Set up Gmail polling mechanism to check for new emails',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-173',
    platform: 'linear',
    object_type: 'issue',
    title: 'Set up Server-Sent Events for real-time updates',
    body: 'Implement SSE infrastructure for pushing real-time updates',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-171',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create Daily Brief dashboard with action items',
    body: 'Build the Daily Brief view showing categorized action items',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-170',
    platform: 'linear',
    object_type: 'issue',
    title: 'Build unified inbox view with platform tabs',
    body: 'Create the main unified inbox interface combining Gmail and Slack',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-169',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement user feedback loop for category corrections',
    body: 'Build system for users to correct categorizations',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-168',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create action item extraction and transformation service',
    body: 'Build service to extract and transform messages into actionable items',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-166',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement Slack message sending and thread replies',
    body: 'Implement Slack API functionality for sending messages and replies',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-165',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create Slack UI with channel view and thread support',
    body: 'Build Slack-like UI for viewing channels, DMs, and threads',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-164',
    platform: 'linear',
    object_type: 'issue',
    title: 'Build Slack message fetching and conversation history sync',
    body: 'Implement Slack message fetching for channels, DMs, and threads',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-163',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement Slack Events API webhook for real-time messages',
    body: 'Set up Slack Events API webhook to receive real-time messages',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-162',
    platform: 'linear',
    object_type: 'issue',
    title: 'Set up Slack OAuth with bot and user scopes',
    body: 'Implement Slack OAuth flow with both bot and user token scopes',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-161',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement Gmail send and reply API functionality',
    body: 'Implement Gmail API functionality for sending emails and replies',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-160',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create Gmail UI with thread view and message composition',
    body: 'Build Gmail-like UI with cc/bcc functionality',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-159',
    platform: 'linear',
    object_type: 'issue',
    title: 'Build Gmail message fetching and incremental sync',
    body: 'Implement Gmail message fetching with incremental sync using History API',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-158',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement Gmail OAuth connection flow and scope management',
    body: 'Set up Gmail OAuth connection with proper scope management',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-156',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement IndexedDB storage layer for message caching',
    body: 'Create IndexedDB storage layer for client-side message storage',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-154',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create user onboarding flow with company information capture',
    body: 'Build the onboarding flow that captures user and company information',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-153',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement Google OAuth authentication with Next-Auth',
    body: 'Set up Google OAuth authentication for user login/signup',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-152',
    platform: 'linear',
    object_type: 'issue',
    title: 'Set up Next.js project with TypeScript and core dependencies',
    body: 'Initialize the Next.js 14 project with all necessary dependencies',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Done',
  },
  {
    id: 'TEN-151',
    platform: 'linear',
    object_type: 'issue',
    title: 'Investigate Message Storage System Design and State Management',
    body: 'Design an efficient database structure for storing messages',
    actor: 'Jongmin Park',
    timestamp: '2025-09-20',
    status: 'Done',
  },
  {
    id: 'TEN-140',
    platform: 'linear',
    object_type: 'issue',
    title: 'create a unified data schema for loading the messages (gmail, slack)',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-18',
    status: 'Done',
  },
  {
    id: 'TEN-139',
    platform: 'linear',
    object_type: 'issue',
    title: 'load gmail messages through scopes',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-18',
    status: 'Done',
  },
  {
    id: 'TEN-138',
    platform: 'linear',
    object_type: 'issue',
    title: 'bring slack threads that include me into web',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-18',
    status: 'Done',
  },
  {
    id: 'TEN-137',
    platform: 'linear',
    object_type: 'issue',
    title: 'bring mentions from slack onto web',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-18',
    status: 'Done',
  },
  {
    id: 'TEN-136',
    platform: 'linear',
    object_type: 'issue',
    title: 'check on bringing private dms onto the group',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-18',
    status: 'Done',
  },
  {
    id: 'TEN-135',
    platform: 'linear',
    object_type: 'issue',
    title: 'slack channels, 메시지 전부 불러오기',
    body: '',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-18',
    status: 'Done',
  },
  // Canceled issues (19)
  {
    id: 'TEN-178',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement cron job system for scheduled tasks',
    body: 'Set up a cron job system for scheduled tasks like daily briefs',
    actor: '',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-177',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create reminder settings and preferences UI',
    body: 'Build UI for users to configure reminder preferences',
    actor: '',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-176',
    platform: 'linear',
    object_type: 'issue',
    title: 'Build Slack reminder bot for daily briefs',
    body: 'Create a Slack bot that sends daily brief reminders',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-175',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create real-time sync coordinator service',
    body: 'Build a coordinator service that manages real-time updates',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-172',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement responsive design and mobile optimization',
    body: 'Ensure the application is fully responsive',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-167',
    platform: 'linear',
    object_type: 'issue',
    title: 'Implement rule-based message categorization engine',
    body: 'Build a rule-based engine to categorize messages',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-157',
    platform: 'linear',
    object_type: 'issue',
    title: 'Create unified message data model and TypeScript interfaces',
    body: 'Define unified data models and TypeScript interfaces',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-155',
    platform: 'linear',
    object_type: 'issue',
    title: 'Set up Supabase project and database schema',
    body: 'Initialize Supabase project and create the core database schema',
    actor: 'Jongmin Park',
    timestamp: '2025-09-22',
    status: 'Canceled',
  },
  {
    id: 'TEN-150',
    platform: 'linear',
    object_type: 'issue',
    title: 'Socket.IO and SSE communication testing',
    body: 'Jest, Socket.IO Client testing, SSE testing',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-149',
    platform: 'linear',
    object_type: 'issue',
    title: 'Virtual AI response streaming via SSE',
    body: 'SSE streaming, virtual response generation',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-148',
    platform: 'linear',
    object_type: 'issue',
    title: 'Multi-platform message unified storage',
    body: 'PostgreSQL transactions, Socket.IO broadcast',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-147',
    platform: 'linear',
    object_type: 'issue',
    title: 'Email reception detection via Gmail API',
    body: 'Gmail API, Google Cloud Pub/Sub, polling mechanism',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-146',
    platform: 'linear',
    object_type: 'issue',
    title: 'Real-time message reception via Slack Events API',
    body: 'Slack Events API, Webhook endpoints',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-145',
    platform: 'linear',
    object_type: 'issue',
    title: 'Server-to-Slack message transmission',
    body: 'Slack Web API, existing OAuth token utilization',
    actor: 'Cailyn Yong',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-144',
    platform: 'linear',
    object_type: 'issue',
    title: 'Real-time message send/receive via Socket.IO',
    body: 'Socket.IO events, message validation',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-143',
    platform: 'linear',
    object_type: 'issue',
    title: 'Efficient client-server data synchronization',
    body: 'PostgreSQL timestamp queries, REST API',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-142',
    platform: 'linear',
    object_type: 'issue',
    title: 'DB schema extension for real-time chat',
    body: 'PostgreSQL, Supabase, migration scripts',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-141',
    platform: 'linear',
    object_type: 'issue',
    title: 'SSE streaming endpoint implementation',
    body: 'Express.js SSE, EventSource compatibility',
    actor: 'Jongmin Park',
    timestamp: '2025-09-19',
    status: 'Canceled',
  },
  {
    id: 'TEN-134',
    platform: 'linear',
    object_type: 'issue',
    title: 'Socket.IO Server Setup and Basic Infrastructure',
    body: 'Socket.IO, Express.js, TypeScript, CORS configuration',
    actor: 'Jongmin Park',
    timestamp: '2025-09-17',
    status: 'Canceled',
  },
];

export async function GET() {
  const doneCount = MOMO_LINEAR_DATA.filter((i) => i.status === 'Done').length;
  const canceledCount = MOMO_LINEAR_DATA.filter((i) => i.status === 'Canceled').length;

  return NextResponse.json({
    items: MOMO_LINEAR_DATA,
    summary: {
      total: MOMO_LINEAR_DATA.length,
      done: doneCount,
      canceled: canceledCount,
      project: 'Momo v4.',
    },
  });
}
